### ISSUE TITLE
Can't Query Wordpress

### ISSUE THREAD

**Issue by bryananthonylewis** [GatsbyCentral/gatsby-starter-wordpress#1]
I've got the WordPress plugin installed ("gatsby-source-wordpress": "^2.0.58") but every time I go to http://localhost:8000/___graphql and try to query allWordpressPost I get this error: 

GraphQL Error There was an error while compiling your site's GraphQL queries.
  Invariant Violation: GraphQLParser: Unknown field `allWordpressPost` on type `RootQueryType`. Source: document `IndexQuery` file: `GraphQL request`.

Did I install the something incorrect?  Seems like the gatsby-source-wordpress plugin isn't working right. But, I'm new to this. Thoughts?

**Comment by Twitchkidd** [comment]
Do you have the server running?

**Comment by bryananthonylewis** [comment]
My WordPress site is live on the web. My localhost is also running, yes.

**Comment by mindofjonas** [comment]
@bryananthonylewis I had this issue when using a new install of WordPress.  The 'Hello World' post doesn't have a featured image by default (it's `0` in the Rest API response) so the`featured_media` object in the graphql doesn't resolve - causing the build to break. The fix is to either remove `featured_media` if you won't be using it when displaying a post or adding a featured image to your posts before running the initial build.
 
See [Allow non-existing fields in GraphQL Queries](https://github.com/gatsbyjs/gatsby/issues/2392) for Gatsby's limitations on this

**Comment by b0gd4n** [comment]
this does not seem to help me - still getting `TypeError: Cannot read property 'allWordpressPost' of undefined` at `const postEdges = this.props.data.allWordpressPost.edges`

**Comment by mindofjonas** [comment]
@bryananthonylewis if the build completes try running in the query at the bottom of that component at `http://localhost:8000/___graphql`. If there are any errors in your schema it should show up in the response.

**Comment by chmac** [comment]
Was this issue resolved? It depends on which WordPress site you are using as your source. Try clicking the "Docs" link in the top right, this will let you explore the schema to see what it looks like.

I'll close this issue assuming that you've either resolved your issues or moved on. If you're still having issues, please open a new issue and we'll do our best to help resolve them.
