### ISSUE TITLE
How can I fetch a new post?

### ISSUE THREAD

**Issue by mostafasoufi** [GatsbyCentral/gatsby-starter-wordpress#42]
Hi there,

Is it possible to fetch post automatically? or should be I run `gatsby build` after new posts?

Thank you

**Comment by chmac** [comment]
The `gatsby build` process needs to be run every time content on your WP site changes. There are some webhook plugins for WordPress which can generate an HTTP call on every change I believe. If you're using something like netlify to build, then you could wire the two things together so that it rebuilds on every content change.
